'use strict';
// Java performs the operations. Browser code only presents recorded snapshots.
const $ = selector => document.querySelector(selector);
const list = value => Array.isArray(value) ? value : [];
const text = value => value == null ? '' : String(value);
const element = (tag, className, value) => { const node=document.createElement(tag);if(className)node.className=className;if(value!=null)node.textContent=text(value);return node; };
const state={labs:[],lab:null,drafts:new Map(),trace:null,frames:[],position:0,timer:null,busy:false,controller:null,request:0,intent:0,codeOpen:false,sourceController:null,sourceRequest:0,sourceFile:null,sourceLoadingFile:null,sourceCache:new Map()};
const svgNS='http://www.w3.org/2000/svg';
function svgElement(tag,attributes={},value){const node=document.createElementNS(svgNS,tag);Object.entries(attributes).forEach(([key,val])=>node.setAttribute(key,text(val)));if(value!=null)node.textContent=text(value);return node;}
function error(message){$('#error-message').textContent=message;$('#error-message').hidden=!message;}
function connection(online){$('#connection-dot').classList.toggle('online',online);$('#connection-dot').classList.toggle('offline',!online);$('#connection-text').textContent=online?'Java connected':'Java unavailable';}
function currentInput(){return {lab:state.lab?.id||'',initial:$('#initial').value,operations:$('#operations').value};}
function operationLines(){return $('#operations').value.split(/\r?\n/).map(line=>line.trim()).filter(Boolean);}
function saveDraft(){if(state.lab)state.drafts.set(state.lab.id,currentInput());}
function controls(){const last=state.frames.length-1;$('#play').disabled=!state.lab||state.busy||Boolean(state.trace&&last<=0);$('#next').disabled=!state.lab||state.busy||Boolean(state.trace&&state.position>=last);$('#previous').disabled=state.busy||!state.frames.length||state.position<=0;$('#reset').disabled=!state.lab;$('#play').textContent=state.timer?'Pause':'Play';$('#play').setAttribute('aria-label',state.timer?'Pause':'Play');$('#desktop-status').textContent=state.busy?'Preparing…':state.frames.length?`Step ${state.position} of ${last}`:state.lab?'Ready':'Connecting…';}
function pause(){clearInterval(state.timer);state.timer=null;controls();}
function cancelTrace(){state.request++;state.controller?.abort();state.controller=null;state.busy=false;}
function cancelSource(){state.sourceRequest++;state.sourceController?.abort();state.sourceController=null;state.sourceFile=null;state.sourceLoadingFile=null;}
function renderQueue(){const values=state.trace?list(state.trace.operations):operationLines();const fragment=document.createDocumentFragment();values.forEach((value,index)=>{const row=element('li');row.append(element('span','queue-index',String(index+1).padStart(2,'0')),element('span','queue-operation',value),element('span','queue-state','waiting'));fragment.append(row);});$('#operation-queue').replaceChildren(fragment);$('#queue-empty').hidden=values.length>0;$('#queue-empty').textContent='Add an instruction above to change the structure.';}
function sourceReference(){const frame=state.frames[state.position],source=frame?.source;$('#source-reference').textContent=source?`${source.file} · line ${source.line}${frame.operation?' · '+frame.operation:''}`:'The highlighted line follows each recorded Java step.';}
function pending(){state.trace=null;state.frames=[];state.position=0;$('#visualization').replaceChildren(element('p','memory-empty','Press Play or Next to see your initial structure.'));$('#view-summary').textContent='Your initial values are used when you begin.';$('#phase-tag').textContent='Ready';$('#step-counter').textContent='0 / 0';$('#step-title').textContent='Ready to begin';$('#operation-label').textContent='';$('#step-message').textContent='Play follows the instructions automatically. Next advances one recorded step.';$('#step-explanation').textContent='Reset returns to your initial values and keeps your instructions.';$('#run-status').textContent='Press Play or Next to begin.';renderQueue();sourceReference();highlightSource();controls();}
function inputChanged(){saveDraft();state.intent++;pause();cancelTrace();error('');pending();if(state.codeOpen)ensureSource();}
async function readJson(response){let data;try{data=await response.json();}catch{throw new Error('Java returned an unreadable response. Restart the local app and try again.');}if(!response.ok)throw new Error(data.error||`The request failed (${response.status}).`);return data;}
async function prepare(){if(state.trace)return true;if(!state.lab)return false;const request=++state.request,controller=new AbortController();state.controller=controller;state.busy=true;error('');$('#run-status').textContent='Preparing your instructions…';controls();let timedOut=false;const timeout=setTimeout(()=>{timedOut=true;controller.abort();},20000);try{const response=await fetch('/api/trace',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:new URLSearchParams(currentInput()),signal:controller.signal});const data=await readJson(response);if(request!==state.request)return false;if(!Array.isArray(data.frames)||!Array.isArray(data.operations))throw new Error('The Java trace is incomplete. Please restart the local app and try again.');state.trace=data;state.frames=data.frames;state.position=0;connection(true);$('#run-status').textContent=state.frames.length?`${data.operations.length} instruction${data.operations.length===1?'':'s'} · ${Math.max(0,state.frames.length-1)} recorded steps`:'Java returned no execution frames.';renderQueue();if(state.frames.length)renderFrame();else{$('#visualization').replaceChildren(element('p','memory-empty','No execution frames were returned. Edit the instructions or press Reset to retry.'));$('#phase-tag').textContent='No frames';$('#step-title').textContent='No execution frames';$('#step-message').textContent='Java returned an empty trace. Try another instruction sequence.';$('#step-explanation').textContent='';$('#step-counter').textContent='0 / 0';$('#view-summary').textContent='No snapshot to display.';}return state.frames.length>0;}catch(caught){if(request!==state.request)return false;const offline=caught.name==='TypeError'||timedOut;if(offline)connection(false);error(offline?'Java is not responding. Start the local app, then press Play or Next again.':caught.message);$('#run-status').textContent='Could not prepare the instructions.';return false;}finally{clearTimeout(timeout);if(request===state.request){state.busy=false;state.controller=null;controls();}}}
function cells(view){const row=element('div','node-cells');list(view.nodes).forEach(node=>{const cell=element('div','data-cell'+(node.active?' active':'')+(node.muted?' muted':''));cell.append(element('span','cell-id',node.id),element('strong','cell-label',node.label),element('span','cell-detail',node.detail));cell.setAttribute('aria-label',`${text(node.id)}: ${text(node.label)} ${text(node.detail)}${node.active?', active':''}`);row.append(cell);});return row;}
function wrapNodeText(value, limit) {
  const result=[];
  for(const paragraph of text(value).split(/\r?\n/)) {
    let line='';
    for(let word of paragraph.split(/\s+/).filter(Boolean)) {
      if(line && line.length+1+word.length>limit){result.push(line);line='';}
      while(word.length>limit){if(line){result.push(line);line='';}result.push(word.slice(0,limit));word=word.slice(limit);}
      if(word)line+=(line?' ':'')+word;
    }
    if(line)result.push(line);
  }
  return result;
}
function nodeText(node) {
  return {id:wrapNodeText(node.id,22),label:wrapNodeText(node.label,18),detail:wrapNodeText(node.detail,22)};
}
function layoutNodes(view) {
  const nodes=list(view.nodes),positions=new Map(),nodeWidth=180;
  const nodeHeight=Math.max(86,...nodes.map(node=>{const parts=nodeText(node);return 26+parts.id.length*13+parts.label.length*18+(parts.detail.length?8+parts.detail.length*15:0);}));
  const horizontalGap=90,verticalGap=82,stepX=nodeWidth+horizontalGap,stepY=nodeHeight+verticalGap;
  if(view.layout==='list') {
    const available=Math.max(320,$('#memory-view').clientWidth-32);
    const columns=Math.min(5,Math.max(1,nodes.length),Math.max(1,Math.floor((available-50+horizontalGap)/stepX)));
    nodes.forEach((node,index)=>positions.set(text(node.id),{x:32+(index%columns)*stepX,y:38+Math.floor(index/columns)*stepY}));
  } else if(view.layout==='tree') {
    const byId=new Map(nodes.map(node=>[text(node.id),node])),children=new Map(nodes.map(node=>[text(node.id),[]]));
    nodes.forEach(node=>{if(byId.has(text(node.parent))&&text(node.parent)!==text(node.id))children.get(text(node.parent)).push(node);});
    const seen=new Set();let nextLeaf=0;
    function place(node,depth,path) {
      const id=text(node.id);if(seen.has(id)||path.has(id))return null;
      path=new Set(path);path.add(id);seen.add(id);
      const placed=list(children.get(id)).map(child=>place(child,depth+1,path)).filter(Boolean);
      const x=placed.length?(placed[0].x+placed[placed.length-1].x)/2:32+nextLeaf++*stepX;
      const point={x,y:38+depth*stepY};positions.set(id,point);return point;
    }
    nodes.filter(node=>!byId.has(text(node.parent))||text(node.parent)===text(node.id)).forEach(node=>place(node,0,new Set()));
    nodes.forEach(node=>{if(!seen.has(text(node.id)))place(node,0,new Set());});
  } else {
    const count=nodes.length,radius=count<=1?0:Math.max(125,(Math.max(nodeWidth,nodeHeight)+45)*count/(2*Math.PI));
    nodes.forEach((node,index)=>{const angle=-Math.PI/2+index*2*Math.PI/Math.max(1,count);positions.set(text(node.id),{x:Math.cos(angle)*radius,y:Math.sin(angle)*radius});});
    const minX=Math.min(0,...[...positions.values()].map(point=>point.x)),minY=Math.min(0,...[...positions.values()].map(point=>point.y));
    positions.forEach(point=>{point.x+=32-minX;point.y+=38-minY;});
  }
  const width=Math.max(220,...[...positions.values()].map(point=>point.x+nodeWidth+32));
  const height=Math.max(120,...[...positions.values()].map(point=>point.y+nodeHeight+26));
  return {positions,width,height,nodeWidth,nodeHeight};
}
function drawDiagram(view){const layout=layoutNodes(view),{positions,width,height,nodeWidth,nodeHeight}=layout;const wrapper=element('div','diagram-scroll');const svg=svgElement('svg',{class:'structure-diagram',width,height,viewBox:`0 0 ${width} ${height}`,role:'img','aria-label':`${view.layout} snapshot with ${list(view.nodes).length} nodes`});const defs=svgElement('defs');for(const [id,color] of [['arrow','#777'],['arrow-active','#000080']]){const marker=svgElement('marker',{id,viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:6,markerHeight:6,orient:'auto-start-reverse'});marker.append(svgElement('path',{d:'M 0 0 L 10 5 L 0 10 z',fill:color}));defs.append(marker);}svg.append(defs);list(view.edges).forEach((edge,index)=>{const start=positions.get(text(edge.from)),end=positions.get(text(edge.to));if(!start||!end)return;const a={x:start.x+nodeWidth/2,y:start.y+nodeHeight/2},b={x:end.x+nodeWidth/2,y:end.y+nodeHeight/2};const dx=b.x-a.x,dy=b.y-a.y;const scale=1/Math.max(Math.abs(dx)/(nodeWidth/2+3),Math.abs(dy)/(nodeHeight/2+3),1);const sx=a.x+dx*scale,sy=a.y+dy*scale,ex=b.x-dx*scale,ey=b.y-dy*scale;let path,mx=(sx+ex)/2,my=(sy+ey)/2;if(edge.from===edge.to){path=`M ${a.x+30} ${start.y} C ${a.x+95} ${start.y-45},${a.x-30} ${start.y-45},${a.x-20} ${start.y}`;mx=a.x+20;my=start.y-26;}else if(view.layout==='list'&&Math.abs(dy)<5){const direction=dx>=0?-1:1;const curve=direction*(edge.label==='prev'?29:20);path=`M ${sx} ${sy} Q ${mx} ${my+curve*2} ${ex} ${ey}`;my+=curve;}else{path=`M ${sx} ${sy} L ${ex} ${ey}`;my-=7+(index%2)*2;}svg.append(svgElement('path',{d:path,class:'diagram-edge'+(edge.active?' active':''),'marker-end':`url(#${edge.active?'arrow-active':'arrow'})`}));if(edge.label)svg.append(svgElement('text',{x:mx,y:my,class:'edge-label'},edge.label));});list(view.nodes).forEach(node=>{const p=positions.get(text(node.id));if(!p)return;const group=svgElement('g',{class:'diagram-node'+(node.active?' active':'')+(node.muted?' muted':''),transform:`translate(${p.x},${p.y})`});group.append(svgElement('title',{},`${text(node.id)}: ${text(node.label)} ${text(node.detail)}`));group.append(svgElement('rect',{width:nodeWidth,height:nodeHeight,rx:2}));const parts=nodeText(node);let textY=17;parts.id.forEach(line=>{group.append(svgElement('text',{x:nodeWidth/2,y:textY,class:'node-id'},line));textY+=13;});textY+=3;parts.label.forEach(line=>{group.append(svgElement('text',{x:nodeWidth/2,y:textY,class:'node-label'},line));textY+=18;});if(parts.detail.length)textY+=5;parts.detail.forEach(line=>{group.append(svgElement('text',{x:nodeWidth/2,y:textY,class:'node-detail'},line));textY+=15;});svg.append(group);});wrapper.append(svg);return wrapper;}
function renderView(view={}){const fragment=document.createDocumentFragment();if(list(view.nodes).length)fragment.append(['list','tree','graph'].includes(view.layout)?drawDiagram(view):cells(view));else fragment.append(element('p','diagram-caption','The structure is empty.'));list(view.lanes).forEach(lane=>{const section=element('section','lane');section.append(element('h3','',lane.label));const items=element('div','lane-items');if(!list(lane.items).length)items.append(element('span','diagram-caption','Empty'));list(lane.items).forEach(value=>items.append(element('span','lane-item',value)));section.append(items);fragment.append(section);});list(view.tables).forEach(table=>{const section=element('section','snapshot-table');section.append(element('h3','',table.label));const dom=element('table'),head=element('thead'),heading=element('tr');list(table.columns).forEach(label=>{const cell=element('th','',label);cell.scope='col';heading.append(cell);});head.append(heading);dom.append(head);const body=element('tbody');list(table.rows).forEach(row=>{const tr=element('tr');list(row).forEach(value=>tr.append(element('td','',value)));body.append(tr);});dom.append(body);section.append(dom);fragment.append(section);});if(list(view.output).length){const output=element('section','output-panel');output.append(element('h3','','Output'),element('pre','',view.output.join('\n')));fragment.append(output);}$('#visualization').replaceChildren(fragment);$('#view-summary').textContent=text(view.summary)||'A snapshot recorded by the Java program.';}
function renderFrame(){const frame=state.frames[state.position];if(!frame){controls();return;}renderView(frame.view||{});$('#phase-tag').textContent=text(frame.phase)||'Step';$('#step-counter').textContent=`${state.position} / ${Math.max(0,state.frames.length-1)}`;$('#step-title').textContent=text(frame.title)||'Execution step';$('#operation-label').textContent=text(frame.operation);$('#step-message').textContent=text(frame.message);$('#step-explanation').textContent=text(frame.note);const operationIndex=Number.isInteger(frame.operationIndex)?frame.operationIndex:-1;const finished=!state.frames.slice(state.position+1).some(next=>next.operationIndex===operationIndex);[...$('#operation-queue').children].forEach((row,index)=>{const current=index===operationIndex,done=index<operationIndex||(current&&finished);row.classList.toggle('current',current);row.classList.toggle('completed',done);if(current)row.setAttribute('aria-current','step');else row.removeAttribute('aria-current');row.querySelector('.queue-state').textContent=current?(done?'done':text(frame.phase)):done?'✓':'waiting';});sourceReference();if(state.codeOpen)ensureSource();else highlightSource();controls();}
function stepTo(position){if(!state.frames.length)return;state.position=Math.max(0,Math.min(position,state.frames.length-1));renderFrame();}
async function next(){const intent=++state.intent;pause();if(await prepare()&&intent===state.intent)stepTo(state.position+1);}
async function play(){const intent=++state.intent;if(state.timer){pause();return;}if(!await prepare()||intent!==state.intent||state.frames.length<=1)return;if(state.position>=state.frames.length-1)stepTo(0);stepTo(state.position+1);if(state.position>=state.frames.length-1)return;state.timer=setInterval(()=>{stepTo(state.position+1);if(state.position>=state.frames.length-1)pause();},950);controls();}
async function reset(){const intent=++state.intent;pause();cancelTrace();error('');if(state.trace&&state.frames.length){stepTo(0);return;}state.trace=null;if(await prepare()&&intent===state.intent)stepTo(0);}
function highlightSource(){document.querySelectorAll('.source-line.active-line').forEach(line=>{line.classList.remove('active-line');line.removeAttribute('aria-current');});const source=state.frames[state.position]?.source;if(!source||source.file!==state.sourceFile)return;const line=[...$('#source-code').children].find(item=>Number(item.dataset.line)===Number(source.line));if(!line)return;line.classList.add('active-line');line.setAttribute('aria-current','true');if(state.codeOpen){const panel=$('#source-code'),top=line.offsetTop-panel.offsetTop;if(top<panel.scrollTop+35||top>panel.scrollTop+panel.clientHeight-65)panel.scrollTop=Math.max(0,top-panel.clientHeight*.4);}}
function showSource(data,file){state.sourceFile=file;$('#source-filename').textContent=data.file||file;const fragment=document.createDocumentFragment();text(data.content).split(/\r?\n/).forEach((content,index)=>{const row=element('div','source-line'+(/^\s*(\/\/|\*|\/\*)/.test(content)?' comment':/^\s*(import|package)\b/.test(content)?' import':''));row.dataset.line=String(index+1);row.append(element('span','line-number',index+1),element('span','line-content',content||' '));fragment.append(row);});$('#source-code').replaceChildren(fragment);highlightSource();}
async function ensureSource(){if(!state.codeOpen||!state.lab)return;const file=text(state.frames[state.position]?.source?.file||state.lab.sourceFile);if(!file)return;if(state.sourceFile===file){if(state.sourceLoadingFile&&state.sourceLoadingFile!==file){state.sourceRequest++;state.sourceController?.abort();state.sourceController=null;state.sourceLoadingFile=null;}highlightSource();return;}if(state.sourceLoadingFile===file)return;const request=++state.sourceRequest,lab=state.lab.id;state.sourceController?.abort();const controller=new AbortController();state.sourceController=controller;state.sourceLoadingFile=file;$('#source-error').hidden=true;$('#source-filename').textContent=file;if(state.sourceCache.has(file)){showSource(state.sourceCache.get(file),file);state.sourceLoadingFile=null;state.sourceController=null;return;}$('#source-code').replaceChildren(element('p','code-empty','Loading source…'));const timeout=setTimeout(()=>controller.abort(),15000);try{const data=await readJson(await fetch('/api/source?file='+encodeURIComponent(file),{signal:controller.signal}));if(request!==state.sourceRequest||lab!==state.lab?.id||!state.codeOpen)return;if(typeof data.content!=='string')throw new Error('The source response is incomplete.');state.sourceCache.set(file,data);showSource(data,file);}catch(caught){if(request!==state.sourceRequest||lab!==state.lab?.id)return;$('#source-error').textContent=caught.name==='AbortError'?'Source loading timed out. Hide and show code to retry.':caught.message;$('#source-error').hidden=false;$('#source-code').replaceChildren(element('p','code-empty','The visualization is still available. Hide and show code to retry.'));}finally{clearTimeout(timeout);if(request===state.sourceRequest){state.sourceController=null;state.sourceLoadingFile=null;}}}
function selectLab(id,updateURL=true){const selected=state.labs.find(lab=>lab.id===id)||state.labs.find(lab=>lab.id==='link')||state.labs[0];if(!selected)return;saveDraft();state.intent++;pause();cancelTrace();cancelSource();state.lab=selected;$('#project').value=selected.id;const draft=state.drafts.get(selected.id);$('#initial').value=draft?.initial??text(selected.initial);$('#operations').value=draft?.operations??(Array.isArray(selected.operations)?selected.operations.join('\n'):text(selected.operations));$('#initial-label').textContent=selected.initialLabel||'Initial values';$('#project-subtitle').textContent=text(selected.subtitle);$('#visual-title').textContent=text(selected.title);$('#operation-help').textContent=Array.isArray(selected.help)?selected.help.join('\n'):typeof selected.help==='object'?Object.entries(selected.help||{}).map(([key,val])=>`${key}: ${text(val)}`).join('\n'):text(selected.help);$('#initial').disabled=false;$('#operations').disabled=false;$('#source-code').replaceChildren(element('p','code-empty','Source appears here.'));$('#source-error').hidden=true;error('');pending();if(updateURL){const url=new URL(location.href);url.searchParams.set('lab',selected.id);history.replaceState(null,'',url);}if(state.codeOpen)ensureSource();prepare();}
async function loadLabs(){error('');$('#retry-labs').hidden=true;const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),15000);try{const data=await readJson(await fetch('/api/labs',{signal:controller.signal}));const labs=Array.isArray(data)?data:list(data.labs);if(!labs.length)throw new Error('No projects are available from the Java server.');state.labs=labs;const fragment=document.createDocumentFragment();labs.forEach(lab=>{const option=element('option','',lab.title);option.value=lab.id;fragment.append(option);});$('#project').replaceChildren(fragment);$('#project').disabled=false;connection(true);selectLab(new URL(location.href).searchParams.get('lab')||'link');}catch(caught){connection(false);error(caught.name==='AbortError'?'The Java server did not respond. Start the local app and retry.':caught.message);$('#run-status').textContent='Could not load projects.';$('#retry-labs').hidden=false;}finally{clearTimeout(timeout);controls();}}
$('#initial').addEventListener('input',inputChanged);$('#operations').addEventListener('input',inputChanged);$('#project').addEventListener('change',()=>selectLab($('#project').value));$('#play').addEventListener('click',play);$('#next').addEventListener('click',next);$('#previous').addEventListener('click',()=>{state.intent++;pause();stepTo(state.position-1);});$('#reset').addEventListener('click',reset);$('#retry-labs').addEventListener('click',loadLabs);$('#toggle-code').addEventListener('click',()=>{state.codeOpen=!state.codeOpen;$('#workspace').classList.toggle('show-code',state.codeOpen);$('#code-panel').hidden=!state.codeOpen;$('#toggle-code').textContent=state.codeOpen?'Hide code':'Show code';$('#toggle-code').setAttribute('aria-expanded',String(state.codeOpen));if(state.codeOpen)ensureSource();else cancelSource();});$('#title-help').addEventListener('click',()=>$('#about-dialog').showModal());$('#close-about').addEventListener('click',()=>$('#about-dialog').close());window.addEventListener('popstate',()=>selectLab(new URL(location.href).searchParams.get('lab')||'link',false));window.addEventListener('pagehide',()=>{pause();cancelTrace();cancelSource();});loadLabs();
